# Generated by Django 5.1.1 on 2024-11-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='Western Visayas', max_length=50)),
                ('province', models.CharField(default='Iloilo', max_length=100)),
                ('municipality', models.CharField(default='Iloilo City', max_length=100)),
                ('dru', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('dru_type', models.CharField(choices=[('rhu', 'RHU'), ('ho', 'CHO/MHO/PHO'), ('gov_hsptl', 'Government Hospital'), ('priv_hsptl', 'Private Hospital'), ('clinic', 'Clinic'), ('priv_lab', 'Private Laboratory'), ('pub_lab', 'Public Laboratory'), ('sea_air', 'Seaport/Airport')], max_length=20)),
            ],
        ),
    ]
