# Generated by Django 5.1.1 on 2024-11-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('date_con', models.DateField()),
                ('is_admt', models.BooleanField()),
                ('date_onset', models.DateField()),
                ('clncl_class', models.CharField(choices=[('N', 'No warning signs'), ('W', 'With warning signs'), ('S', 'Severe dengue')], max_length=100)),
                ('ns1_result', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative'), ('E', 'Equivocal'), ('PR', 'Pending Result')], max_length=100)),
                ('date_ns1', models.DateField(default=None, null=True)),
                ('igg_elisa', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative'), ('E', 'Equivocal'), ('PR', 'Pending Result')], max_length=2)),
                ('date_igg_elisa', models.DateField(default=None, null=True)),
                ('igm_elisa', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative'), ('E', 'Equivocal'), ('PR', 'Pending Result')], max_length=2)),
                ('date_igm_elisa', models.DateField(default=None, null=True)),
                ('pcr', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative'), ('E', 'Equivocal'), ('PR', 'Pending Result')], max_length=2)),
                ('date_pcr', models.DateField(default=None, null=True)),
                ('case_class', models.CharField(choices=[('S', 'Suspect'), ('P', 'Probable'), ('C', 'Confirmed')], max_length=1)),
                ('outcome', models.CharField(choices=[('A', 'Alive'), ('D', 'Dead')], max_length=1)),
                ('date_death', models.DateField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('ca_house_no', models.IntegerField()),
                ('ca_street', models.CharField(max_length=100)),
                ('ca_barangay', models.CharField(max_length=100)),
                ('ca_city', models.CharField(max_length=100)),
                ('ca_province', models.CharField(max_length=100)),
                ('p_house_no', models.IntegerField()),
                ('p_street', models.CharField(max_length=100)),
                ('p_barangay', models.CharField(max_length=100)),
                ('p_city', models.CharField(max_length=100)),
                ('p_province', models.CharField(max_length=100)),
                ('civil_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('SEP', 'Separated')], max_length=3)),
                ('date_first_vax', models.DateField(null=True)),
                ('date_last_vax', models.DateField(null=True)),
            ],
        ),
    ]
